apiVersion: v1
entries:
  sensitive-data:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2020-05-27T16:23:45.749762278Z"
    description: Sensitive-data is a service that searches for sensitive data in HTTP
      request/responses, both in headers and body.
    digest: 530b44bcc099f91202ca42c547a187a9763e9ff73d8a2d7d0a20f25378880f26
    home: https://github.com/BBVA/apicheck
    maintainers:
    - email: security.group@bbva.com
      name: Innovation4security@bbva.com
      url: https://github.com/BBVA/apicheck
    name: sensitive-data
    sources:
    - https://github.com/BBVA/apicheck
    type: application
    urls:
    - sensitive-data-1.0.0.tgz
    version: 1.0.0
generated: "2020-05-27T16:23:45.749220373Z"
