apiVersion: v1
entries:
  sensitive-data:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2020-05-28T05:50:02.06417955Z"
    description: Sensitive-data is a service that searches for sensitive data in HTTP
      request/responses, both in headers and body.
    digest: 6daec8e8dff855d1ca1a97f43d70342efc66c19685a45bdc486d1895c51b1c53
    home: https://github.com/BBVA/apicheck
    maintainers:
    - email: security.group@bbva.com
      name: Innovation4security@bbva.com
      url: https://github.com/BBVA/apicheck
    name: sensitive-data
    sources:
    - https://github.com/BBVA/apicheck
    type: application
    urls:
    - sensitive-data-1.0.0.tgz
    version: 1.0.0
generated: "2020-05-28T05:50:02.063584149Z"
